### ISSUE TITLE
Shows same top predicted result text for different images 

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-crowdsource-dnn-optimization#18] opened 2017-02-09 06:45 UTC
Shows same top predicted result text for different images 
but if over this text with mouse hint shows correct text:
![image](https://cloud.githubusercontent.com/assets/22045452/22772176/d1417974-eecd-11e6-8d33-000307936f04.png)

![image](https://cloud.githubusercontent.com/assets/22045452/22772339/a97e8412-eece-11e6-8c13-849db30ec529.png)

![20170209_135055](https://cloud.githubusercontent.com/assets/22045452/22772556/d4374b5c-eecf-11e6-9450-5829bfc50b9f.jpg)

**Comment by dsavenko** [comment] 2017-02-17 11:12
Can't reproduce. Let's wait @DVEfremov

**Comment by dsavenko** [comment] 2017-03-15 08:20
There was an issue when sometimes UI widgets were updated from a non-UI thread. Most likely, this problem was caused by that. That was fixed with the redesign. So, closing this ticket. If the problem arise again, we can reopen it.

**Closed as completed by dsavenko** 2017-03-15 08:20 UTC
Labels: bug
